---
title: "Deliverable 3 Data Analyses"
output: uhhh
date: "2024-03-14"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```

## ANOVA comparing temperature and mosquito pathogen positivity across sites

```{r}
# Loading appropriate packages

library(tidyverse)
library(here)
library(cowplot)
library(viridis)
```

```{r}
# Read in data
temp_day <- read_csv(here("data", "processed", "temp_day.csv"))
mosquito_clean <- read_csv(here("data", "processed", "mosquito_clean.csv"))
rodent_clean <- read_csv(here("data", "processed", "rodent_clean.csv"))
```

```{r}
#Convert rodent and mosquito test data into binary values
mosquito_binary <- mosquito_clean %>% 
  mutate(testResult_mos= ifelse(testResult=="Positive",1,0),
         collectDate = floor_date(endCollectDate, "day")) %>% 
  select(-startCollectDate, -endCollectDate)

rodent_binary <- rodent_clean %>% 
  mutate(testResult_rodent= ifelse(testResult=="Positive",1,0))
```

```{r}
#Saving positive/negative binary data to processed data folder
mosquito_binary %>% 
  write_csv(here("data", "processed", "mosquito_binary.csv"))

rodent_binary %>% 
  write_csv(here("data", "processed", "rodent_binary.csv"))
```

```{r}
#Join data sheets
mosquito_day <- mosquito_clean %>% 
  select(-startCollectDate) %>% 
  mutate(collectDate = as_date(endCollectDate)) %>% 
  select(-endCollectDate) 

temp_day_join <-temp_day %>% 
  rename("collectDate"= `floor_date(startDateTime, "day")`)

temp_mos_raw <-
  full_join(mosquito_binary, temp_day_join) %>% 
  select(-testResult)

temp_mos_raw #%>% 
  #write_csv(here("data", "processed", "temp_mos_raw.csv"))

temp_mos_season <- temp_mos_raw %>% 
  drop_na() %>% 
  subset %>% 
  mutate(month = month(collectDate),
         season = ifelse(month %in% c(06,07,08), "summer",
                         ifelse(month %in% c(09,10,11), "fall",
                                ifelse(month %in% c(12,01,02), "winter",
                                        ifelse(month %in% c(03,04,05), "spring",
                                                "NA"))))) %>% 
  group_by(siteID, season, testResult_mos) %>% 
  summarize(total = n())

temp_mos_season

```

```{r}
#Performing an ANOVA on test results with season and site id
model1 <- aov(testResult_mos ~ siteID * season, data = temp_mos_season)

summary(model1)
TukeyHSD(model1)

par(mfrow = c(1, 2))
plot(model1, which = c(2, 3))

#Additive model
additive_model <- aov(testResult_mos ~ siteID + season, data = temp_mos_season)

summary(additive_model)
TukeyHSD(additive_model)

par(mfrow = c(1, 2))
plot(additive_model, which = c(2, 3))

#We performed a two-way ANOVA to test whether the proportion of positive 
#mosquito test results were not associated with the site ID, the season of the year, 
#or the interaction of the two. None of the variables listed above had a 
#significant relationship (all p values > 0.85).
```

```{r}
ggplot(data = temp_mos_season, 
         aes(x = season, 
             y = testResult_mos)) +
    geom_jitter(aes(col = siteID),
          width = 0.2) +

  scale_y_continuous(limits =  c(0, 0.1)) +
  theme_bw()
  
```



