---
title: "Consolidated data grab from NEON portal"
author: "Anderson Smith"
date: "2024-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load packages


```{r load libraries, message = FALSE}

library(tidyverse)
library(neonUtilities)
library(here)

```

##Assign names to codes, sites, and date ranges


```{r}

# Temperature data
temperature <- "DP1.00003.001"

# Mosquito Pathogen Status
mosquito <- "DP1.10041.001"

# Focal sites
my_sites <- c("DSNY", "HARV", "MOAB","WOOD")

# Start date (as YYYY-MM)
start_date <- "2016-04" 

# End date (as YYYY-MM)
end_date <- "2022-10" 

```

# Temperature: 

# Pull temperature data from NEON

```{r}

# Dowloading temperature data
list2env((loadByProduct(dpID = temperature, 
                        site = my_sites, 
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)

```
# Write metadata and raw data as a CSV
```{r save metadata csv}

# Variable names and units: temperature
variables_00003 %>% 
  write_csv(here("Data", "Raw", "variables_00003.csv"))

# Raw data: triple-aspirated air temp, 30min intervals
TAAT_30min %>% 
  write_csv(here("Data", "Raw", "TAAT_30min.csv"))
```

# Mosquito pathogen status: 

## Pull mosquito data from NEON
```{r} 

list2env((loadByProduct(dpID = mosquito, 
                        site = my_sites, 
                        include.provisional = TRUE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```

## Write metadata and raw data files as a CSV
```{r}
# putting variable data in raw folder
variables_10041 %>% 
  write_csv(here("data", "raw", "variables_10041.csv"))
```

```{r}
# putting mosquito data in raw folder
mos_pathogenpooling %>% 
  write_csv(here("data", "raw", "mos_pathogenpooling.csv"))
```

```{r}
# putting mosquito data in raw folder
mos_pathogenresults %>% 
  write_csv(here("data", "raw", "mos_pathogenresults.csv"))
```