---
title: "Uniting Mosquito, Rodent, and Temperature Datasets"
author: "Anderson Smith"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Preliminary cleaning/wrangling of NEON data for analysis

Grabbing temperature, rodent, and mosquito data to test climatic (latitudinal)
variation in viral pathogen load

```{r, echo == FALSE}
#Load packages and raw data
library(tidyverse)
library(here)
library(lubridate)

temp_raw <- read_csv(here("Data", "Raw", "TAAT_30min.csv"))

mosquito_path_raw <- read_csv(here("Data", "Raw", "mos_pathogenresults.csv"))

rodent_raw <- read_csv(here("Data", "Raw", "rpt_bloodtesting.csv"))

```

##Cleaning each tibble:

```{r}
#Clean temperature 
temp_clean <- temp_raw %>% 
  select(siteID, startDateTime, endDateTime, tempTripleMean, tempTripleMaximum,
         tempTripleMinimum, tempTripleVariance) %>% 
  drop_na()

#Clean mosquitoes
mosquito_clean <- mosquito_path_raw %>% 
  select(siteID, testResult, testPathogenName, taxonID, startCollectDate,
         endCollectDate) %>% 
  drop_na() %>% 
  mutate(testResult = as_factor(testResult))

#Clean rodents
rodent_clean <- rodent_raw %>% 
  select(siteID, collectDate, testResult) %>% 
  mutate(testResult = as_factor(testResult))
  
```

```{r}
#Group temperature by day 
temp_day <- temp_clean %>% 
  group_by(siteID, floor_date(startDateTime, 'day')) %>% 
  summarize(avg_temp = mean(tempTripleMean), 
            min_temp = mean(tempTripleMinimum),
            max_temp = mean(tempTripleMaximum), 
            var_temp = mean(tempTripleVariance))

temp_month <- temp_clean %>% 
  group_by(siteID, floor_date(startDateTime, 'month')) %>% 
  summarize(avg_temp = mean(tempTripleMean), 
            min_temp = mean(tempTripleMinimum),
            max_temp = mean(tempTripleMaximum), 
            var_temp = mean(tempTripleVariance))
  
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
# Create/check on "processed" data folder, write data into CSV within folder
ifelse(!dir.exists(here("data", "processed")), dir.create(here("data", "processed")), "Folder exists already")

temp_clean %>% 
  write_csv(here("data", "processed", "temp_clean.csv"))

temp_day %>% 
  write_csv(here("data", "processed", "temp_day.csv"))

temp_month %>% 
  write_csv(here("data", "processed", "temp_month.csv"))

rodent_clean %>% 
  write_csv(here("data", "processed", "rodent_clean.csv"))

mosquito_clean %>% 
  write_csv(here("data", "processed", "mosquito_clean.csv"))

```

```{r}
#Preliminary temperature boxplot/jitter by site, save plot
ggplot(temp_month, 
       aes(x = siteID,
       y = avg_temp, 
       col = siteID)) +
  geom_boxplot(alpha = 0) +
  geom_jitter() +
  xlab("Site ID") + ylab("Average Temperature(C)") +
  theme(plot.title = element_text(hjust = 1)) +
  theme_classic() 
  
ifelse(!dir.exists(here ("outputs")), dir.create(here("processed")), "Folder exists already")

  ggsave(filename = "./outputs/prelim_tempplot_site.png", 
       plot = last_plot(), 
       width = 5, height = 3, units = "in",
       dpi = 300)
  
```

```{r}
#Scatter plot for temperature over month
temp_month <- temp_month %>% 
  rename(date = "floor_date(startDateTime, \"month\")")
ggplot(data = temp_month, 
       mapping = aes(x = date,
                     y = avg_temp,
                     col = siteID)) + 
  geom_point() + 
  theme_bw()
```

